"""None author_id

Revision ID: 0f3bac216fb5
Revises: b9aa06eecfe0
Create Date: 2026-01-03 01:00:30.237620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f3bac216fb5'
down_revision: Union[str, Sequence[str], None] = 'b9aa06eecfe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'author_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
